name: Run zi2clash
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    env:
      SUCC: 0
    runs-on: ubuntu-latest
    steps:
      - name: Install zstd & idn2
        run: |
          sudo apt install zstd idn2
      - name: Checkout clash-scripts
        uses: actions/checkout@v3
        with:
          path: clash-scripts
      - name: Checkout clash-conf
        uses: actions/checkout@v3
        with:
          repository: apevogoci/clash-conf
          path: clash-conf
          persist-credentials: false
      - name: Run zi2clash
        run: |
          echo $SUCC
          export CDIR="$(readlink -f "./clash-conf/conf")"
          ./clash-scripts/z-i2clash.sh || echo "SUCC=1" >> $GITHUB_ENV
      - name: Commit changes
        if: ${{ env.SUCC == 0 }}
        run: |
          cat "./commit_msg.txt"
          cd clash-conf
          git config --local user.name "ghactions"
          git add ./conf
          git commit -F "../commit_msg.txt" || echo "SUCC=1" >> $GITHUB_ENV
      - name: Push changes
        if: ${{ env.SUCC == 0 }}
        uses: ad-m/github-push-action@master
        with:
          repository: apevogoci/clash-conf
          github_token: ${{ secrets.CLASH_CONF }}
          directory: clash-conf
          force: true
