name: Run zi2clash
on:
  #schedule:
  #  - cron: '30 * * * *'
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    env:
      SUCC: 0
      CLASHCONF_TOKEN: ${{ secrets.CLASH_CONF }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout clash-scripts
        uses: actions/checkout@v3
        with:
          path: clash-scripts
      - name: Checkout clash-conf
        uses: actions/checkout@v3
        with:
          repository: apevogoci/clash-conf
          path: clash-conf
      - name: Run zi2clash
        run: |
          echo $SUCC
          echo $CLASHCONF_TOKEN | sed -re 's/./_&/g'
          sudo apt install zstd idn2
          export CDIR="$(readlink -f "./clash-conf/conf")"
          ./clash-scripts/zi2clash.sh
      - name: Commit changes
        if: ${{ env.SUCC == 0 }}
        run: |
          cd clash-conf
          git config --local user.name "ghactions"
          git add ./conf
          git commit -m "Updating rules" || echo "SUCC=1" >> $GITHUB_ENV
      - name: Push changes
        if: ${{ env.SUCC == 0 }}
        uses: ad-m/github-push-action@master
        with:
          repository: apevogoci/clash-conf
          github_token: ${{ secrets.CLASH_CONF }}
          force: false
